#!/usr/bin/dh-exec
usr/lib/bazel/install/A-server.jar => usr/share/java/bazel-3.0.0.jar 
usr/lib/bazel/install/build-label.txt
usr/lib/bazel/install/install_base_key
usr/lib/bazel/install/jdk.BUILD
usr/lib/bazel/install/build-runfiles usr/libexec/bazel
usr/lib/bazel/install/daemonize usr/libexec/bazel
usr/lib/bazel/install/libunix.so usr/lib/${DEB_HOST_MULTIARCH}/bazel
usr/lib/bazel/install/linux-sandbox usr/libexec/bazel
usr/lib/bazel/install/process-wrapper usr/libexec/bazel
usr/lib/bazel/install/embedded_tools/*
usr/lib/bazel/install/platforms/*
